### PR TITLE
Fix bug in "require pry"

### PR DESCRIPTION
**Pull request by psousa**
Have no idea why "require pry" was there but it shouldn't. Breaks in production env in Heroku.

### CODE REVIEW

**Comment by paulosilva86** [comment]
:ok:

**Comment by psousa** [comment]
Updated default API endpoint...

**Comment by paulosilva86** [comment]
:ok:

**Comment by donbonifacio** [comment]
@psousa may I ask you to merge master so that I can merge this upstream?

**Comment by psousa** [comment]
@donbonifacio master has the latest (and stable) version of my changes. Lot's of usefull stuff there. Tell me if you need any clarifications.

**Comment by donbonifacio** [comment]
@psousa no need for his PR then? Can I close it?

**Comment by psousa** [comment]
@donbonifacio You should merge the changes from my pull requeste or else the gem is (mostly) broken as it its.

**Comment by donbonifacio** [comment]
I'd like to merge, but I get "We can’t automatically merge this pull request.", there are conflicts. That's why I was asking for an update on your branch.

**Comment by psousa** [comment]
Didn't realize you added changes yesterday. I'll pull those.

**Comment by psousa** [comment]
@donbonifacio should be amazing now.

**Comment by donbonifacio** [comment]
Thanks @psousa :)

**Pull request merged**
