### PR TITLE
Adding owner_invoice_id to CreditNote and DebitNote

### PR DESCRIPTION
**Pull request by igorescobar**
* Adding owner_invoice_id to CreditNote and DebitNote
* Fixing travis.yml

### CODE REVIEW

**Comment by igorescobar** [comment]
@donbonifacio here it is.

**Comment by donbonifacio** [comment]
Thanks @igorescobar !

**Comment by igorescobar** [comment]
@donbonifacio let us know when the new version is available on RubyGems.

**Comment by donbonifacio** [comment]
@igorescobar it's published:
https://rubygems.org/gems/invoicexpress/versions/0.1.10

Please check if everything is ok!

**Comment by igorescobar** [comment]
Nice!

Regards,
Igor Escobar

*Software Engineer*
+ http://blog.igorescobar.com
+ http://www.igorescobar.com
+ @igorescobar <http://www.twitter.com/igorescobar>

**Comment by igorescobar** [comment]
@donbonifacio worked like a charm. ;)

**Comment by donbonifacio** [comment]
Nice @igorescobar :)

If you want to contribute again, you're welcome. :)

**Pull request merged**
