### PR TITLE
owner_invoice_id missing

### PR DESCRIPTION
**Pull request by tiagomatos**

### CODE REVIEW

**Comment by igorescobar** [comment]
@pawel-krysiak is this project still being maintained? This should be merged as pointed in #13

**Comment by igorescobar** [comment]
@donbonifacio @lamuria @tOOnPT please take a look.

**Comment by donbonifacio** [comment]
Ok guys we'll look into this. Meanwhile if you could fix the build it would be great.

**Comment by donbonifacio** [comment]
@tiagomatos can you also add that for `DebitNote` and `Receipt`?

**Comment by igorescobar** [comment]
@donbonifacio Seems that the build broke with something not related to the chances @tiagomatos made.

We are testing this gem against ruby 1.9.3 and we are using a gem on the master which requires ruby 2.0.

screen shot 2016-12-05 at 14 10 34

**Comment by igorescobar** [comment]
@tiagomatos can you add this also for `DebitNote` and `Receipt`?

**Comment by donbonifacio** [comment]
@igorescobar do you have a working env for this? Can you check the `Gemfile.lock` and also set the proper deps for this ruby version?

**Comment by igorescobar** [comment]
@donbonifacio No. I just read the job output here: https://travis-ci.org/weareswat/invoicexpress-gem/jobs/179473240

Seems that this is a existent problem not related to the changes presented here on this PR.

**Comment by donbonifacio** [comment]
Yes, but we can fix it here (or create another PR with the fix and rebase it here). If you guys can do that I'd appreciate.

**Comment by igorescobar** [comment]
@donbonifacio I understand your concern but I think we need to find a middleground here. This is a `production` error and I think we should fix it with some urgency so I strongly encourage us to merge this and then fix the *already existent problem* with more calm. 

@tiagomatos Do you have any intention of fixing this? We are waiting for 5 days :) If you do not, please, just give us a heads up so I can fix it myself and open another PR, close this one and move on.

**Comment by donbonifacio** [comment]
@igorescobar are you suggestion to publish this gem with the dependecies problem? Do you think that will work?

**Comment by igorescobar** [comment]
@donbonifacio The support for Ruby 1.9.3 of ruby has ended on February of 2015 (https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/). I'm not sure why you are trying to keep compatibility with a Ruby version which is not being maintained/supported anymore.

**Comment by igorescobar** [comment]
@donbonifacio So even better, if Ruby 1.9.3 doesn't add much value why support it and require it on Travis CI, Just remove: https://github.com/weareswat/invoicexpress-gem/blob/master/.travis.yml#L6 and move on 🎉

**Comment by donbonifacio** [comment]
I agree @igorescobar . Would like to have this PR succeeding so if @tiagomatos doesn't remove that from the build I will.

**Comment by igorescobar** [comment]
@donbonifacio I will submit a proper PR I a few. Thanks.

**Comment by donbonifacio** [comment]
Implemented here:
https://github.com/weareswat/invoicexpress-gem/pull/22

**Pull request closed without merging**
